# A Github Action that minifies html/css/js and pushes it to a new branch
name: purge-and-minify

# Run on pushes to `main` branch
on:
  push:
    branches:
      - 'main'

permissions:
  contents: write

jobs:
  checkout-minify-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Install CLI tools
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install -g terser
      - run: npm install -g csso-cli
      - run: npm install -g html-minifier

      # Use CLI tools to minify, overwriting existing files
      - run: for i in ./js/*.js; do terser $i --compress --mangle --mangle-props -o $i; done
      - run: for i in ./css/*.css; do csso $i -o $i; done
      - run: for i in ./*.html; do html-minifier --remove-comments $i -o $i; done
      
      # Push changes to `gh-pages` branch
      - run: |
          git config user.name feltocraig
          git config user.email feltocraig@user.noreply.github.com
          git commit -am 'Automated minify of ${{ github.sha }}'
          git push --force -u origin main:gh-pages
